export type { Castle, Check, Mate, PawnCapture, PieceCapture } from './styles.js'
export { CASTLE_STYLES, CHECK_STYLES, MATE_STYLES, PAWN_STYLES, PIECE_STYLES } from './styles.js'
export { type CapturedPiece, castle, check, mate, pawnCapture, pieceCapture } from './map.js'
export { type KingEffect, type Motion, isCastle, isCheck, isMate, isPawnCapture, isPieceCapture } from './classify.js'
export { type KingEffects, type Motions, type Styles, style, styleEffects, styleMotions } from './apply.js'